- hooks/environment
- hooks/post-command
- tests/run.bats
Currently all config is checked in s3 with a `headobject` call. This PR adds an optimization that checks these files via `ls` if possible.
> Use a list if possible, lots of headobject calls are slow

- lib/shared.bash
MacOS sets some strange permissions for anonymous pipes which results in errors on ssh-add.
> Set the permissions on ssh private keys before adding

- hooks/environment
- lib/shared.bash
- tests/run.bats
The optimisation where a bucket list is used rather than trying individual keys really fails on large buckets. At this stage it hurts more than it helps and should be removed. 
Fixes #6.
> Remove the bucket contents listing optimization

- lib/shared.bash
Hi guys,
Running the plugin thought Git for Windows bash interpreter fails with a '/dev/stdout' redirect so I have changed this to a more conventional '-' which tests fine in Windows.
Regards,
Mark.
> Changed output from '/dev/stdout' to '-'

- git-credential-s3-secrets
Hi guys,
Found another Git for Windows Bash-ism which breaks redirect to stdout. I've updated the code for this and tested against my Windows agent. Works a charm.
Mark.
> Replaced '/dev/stdout' with '-' for GfW Bash

- .buildkite/pipeline.yml
- .buildkite/test_credentials.sh
When we moved this to a new repo name it it broke the git-credentials tests. This fixes them.
> Fix broken git-credential test in CI

- hooks/pre-exit
`ssh-agent -k` outputs commands to be `eval`d:
```
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 40249 killed;
```
It should be wrapped in an eval, like `ssh-agent -s`:
```
$ eval "$(ssh-agent -s)"
Agent pid 40270
$ eval "$(ssh-agent -k)"
Agent pid 40270 killed
```
> eval ssh-agent -k

- hooks/environment
- lib/shared.bash
- tests/run.bats
Some folks have reported sporadic failures when fetching their secrets, this shows unexpected errors on the `head-object` check which should surface them better and make troubleshooting possible.
To check this out in an elastic stack, you could have the following in your `bootstrap-script`:
```
rm -rf /usr/local/buildkite-aws-stack/plugins/secrets
git clone https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks.git /usr/local/buildkite-aws-stack/plugins/secrets
pushd /usr/local/buildkite-aws-stack/plugins/secrets
git checkout show-errors-from-head-object
popd
```
> Show unexpected errors from head-object

- hooks/environment
Don't hard-fail when there's no SSH keys found.  The hard-fail was intended to make debugging more obvious, rather than an obscure permission error during `git clone`. However there are legitimate use-cases for enabling this secrets plugin but not fetching an SSH key, for example any combination of:
- `git config url.<base>.insteadOf` can be used to rewrite a `git@...` repo to `https://...` with HTTPS credentials sourced some other way,
- a pipeline may be using the environment part of this secrets plugin, but not the SSH key part.
- an agent may run some pipelines that use this secrets plugin, and some that don't.
This patch;
- removes the `exit 1` hard failure,
- adjusts the BUILDKITE_REPO pattern to not match non-SSH `git://` URLs,
- elaborates on the warning message, with a link to …
> Warn instead of fail when no SSH keys found in S3

- hooks/environment
(hopefully) solves https://github.com/buildkite/elastic-ci-stack-for-aws/issues/637
Sometimes `awscli` fails to connect to the metadata server, erroring with the failure
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
`awscli` can be configured with [metadata_service_num_attempts](https://docs.aws.amazon.com/cli/latest/reference/configure/#configuration-variables), by setting the env var [AWS_METADATA_SERVICE_NUM_ATTEMPTS](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials)
I think 3 attempts is fine (default is 1). There is also a configurable `metadata_service_timeout`, but `metadata_service_num_attempts` should suffice
> add AWS_METADATA_SERVICE_NUM_ATTEMPTS env var

- README.md
* Corrects README to use `private_ssh_key` instead of `ssh_private_key`.
* Misc markdown cleanup.
> ssh_private_key -> private_ssh_key, misc cleanup

- hooks/environment
We've got a customer who is finding that when they set a global environment file as well as a pipeline environment file, the pipeline environment file never gets evaluated. 
We can see that only the global environment file gets downloaded and evaluated but not why the script never gets to the pipeline environment file, hopefully this change will give us some more info about what is actually happening.
> Print more output around downloading environment files

- hooks/environment
if a customer doesn't have one of the env files specified, they don't care if it can't be checked.
Thanks @matthewd for pointing this out!
> Don't exit if can't check env file

- hooks/environment
- lib/shared.bash
- Unused `grep_secrets` function removed.
- looks like it was never even used in the commit d7f96df07773bec972c7557fba6a996e2626135e that introduced it.
- Early exit for no bucket; avoid bulk indentation.
- Best to view the resulting diff [with whitespace ignored](https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/35/files?w=1).
> 🧹 early exit instead of indentation, unused grep_secrets removed.

- s3secrets-helper/sshagent/sshagent.go
Testing shows this works for both keys with and without trailing newlines already.
Fixes #43
> Append a trailing newline to secret keys before sending them to the ssh-agent

- s3secrets-helper/secrets/secrets.go
Escaping the program path adequately (twice!) should fix this issue.
Fixes #46
> Fix credential.helper path when it includes spaces

- git-credential-s3-secrets
This was brought up by shellcheck in the elastic ci stack, so while I’m here fix these up.
> Quote the IDMS address

- .buildkite/pipeline.yml
This step runs an integration test, confirming the compiled plugin helper is able to read a git-credentials file from a real S3 bucket (bucket name is set in an ENV).
It's been a few years since this project was actively developed, however it's still very much used in current elastic stack releases. The test setup has bitrot a little, and the current agents don't have permission to read the test S3 bucket.
Rather than add the required permissions to the Instance Role used by the current agents, I've created an OIDC assumable role that has the rquired S3 permissions. The role is only assumable by this pipeline.
> Assume an IAM role to run integration tests

- .github/dependabot.yml
A couple of things I noticed once #61 started working
* group all updates to the AWS sdk modules (to avoid partial updates like #64)
* tag agent-stewards as reviewers for docker PRs
> tweak dependabot config

- .buildkite/Dockerfile-release
- .buildkite/docker-compose.yml
- .buildkite/pipeline.yml
- .buildkite/steps/github-release.sh
This is a partial revert of commit 90deee4f84d2bf41d8b46ac439ad934605f557f3.
In that commit we changed the release step to run on an experimental agent queue called "on-demand". That queue doesn't exist any more, so releasing is broken.
I've reverted it, but then made some additional changes. Back in 2021 the release step ran on our deploy agents, which had privileged access. That's no longer a pattern we use, so we want to:
* run the step on an standard unprivileged agent
* assume an IAM role via OIDC that has just the permissions we require
* use docker to define the build tools we need
I'm ~80% confident this will just work. it's difficult  to test, because the IAM role can only be assumed by builds that are on `main`. However, I've run a few partial builds on the branch to confirm the …
> Switch release step back to standard agents

- .github/dependabot.yml
It should default to CODEOWNERS.
> dependabot.yml: remove reviewers

- README.md
If the BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX is not specified, the default path for the secret-files will be at  `s3://{bucket_name}/{pipeline}/secret-files/`
> Update README with default path if s3 secrets bucket is not specified

- s3secrets-helper/s3/s3.go
- s3secrets-helper/s3/s3_test.go
Update the s3 tests' reference of AWS SDK to use V2 and renamed back the s3 client to `Client` for consistency with how it is called across the plugin.
> Update aws sdk reference to use v2

- s3secrets-helper/secrets/secrets.go
- s3secrets-helper/secrets/secrets_test.go
If the `secret-files` are specified under the path `s3://{bucket_name}/secret-files/`, these currently do not get included into the list of secret environment variables set.
> Ensure that secret files in path are retrieved from `s3://{bucket_name}/secret-files/` path

- .buildkite/pipeline.yml
Roll out using session tags for OIDC assumable IAM role trust policy.
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dist/pull/130  to be shipped first
Note that one role is restricted to main `branch_builds` only, the other is not restricted by branch.
> Update to use OIDC session tokens on AWS role assumption

- .buildkite/docker-compose.yml
- .buildkite/pipeline.yml
- .buildkite/steps/tests.sh
- README.md
- hooks/environment
- s3secrets-helper/env/env.go
- s3secrets-helper/go.mod
- s3secrets-helper/go.sum
- s3secrets-helper/main.go
- s3secrets-helper/secrets/secrets.go
- s3secrets-helper/secrets/secrets_test.go
- s3secrets-helper/sshagent/sshagent.go
- tests/environment.bats
Adds automatic secret redaction to prevent secrets from appearing in build logs. Uses `buildkite-agent redactor` to register all S3 secrets for redaction before they can be logged.
- Collects all secrets from S3 during the normal fetch process
- Sends secrets to `buildkite-agent redactor add` using JSON batch format
- Splits large secret lists into chunks to handle builds with lots of secrets
- Detects agent version and gracefully handles older versions that don't support redaction
- Provides warnings when redaction is unavailable
> Add secret redaction for all secrets using `buildkite-agent redactor`
